### ISSUE TITLE
【qwq】没看懂如何得到flag

### ISSUE THREAD

**Issue by LiaoJingyi** [NoSparkHere/ZFun2022#3]
[题面](https://github.com/NoSparkHere/ZFun2022/blob/main/Misc/qwq)

从flag推得kaomoji似乎可以用如下[方法](https://github.com/kokororin/kaomojify/blob/master/convert.js)。
但是我不太明白如何在已知kaomoji的条件下推算flag呢？似乎答案不唯一呢。

**Comment by ZeroAurora** [comment]
这道题本质是一个特殊的JSFuck，实质上是一串无效的 JavaScript
至于解法，只要网上搜颜文字编码就行，或者参照 https://github.com/NoSparkHere/ZFun2022/tree/main/WriteUp/Yang#6-1-qwq

**Comment by LiaoJingyi** [comment]
感谢快速回复，原来如此 http://hi.pcmoe.net/kaomoji.html
Interesting
